### ISSUE TITLE
and is public school holiday today in Norway

### ISSUE THREAD

**Issue by SimonSkotheimsvik** [balmli/no.almli.publicholidays#12]
Bjørnar,
I am testing your app in advanced flow, and I get output on NO when testing "is public holiday today in Norway". The schools has been closed for one week+ today 05.07.2022. What is causing this?

**Comment by RoyEssers** [comment]
It seems only limit school holidays are added to holidays_list.js, so that's why it's properly not working as you would expect.

**Comment by balmli** [comment]
That's right.  I think it was a mistake by me to add the "is publish holiday" - condition.  Because it is only supported by a few countries.

**Comment by RoyEssers** [comment]
Well, the idea is nice, but it would take a lot to maintain and keep it accurate. Especially if there're date ranges (like the current summer holiday).

**Comment by balmli** [comment]
"Is school holiday" condition card was removed since v. 1.2.0
