### ISSUE TITLE
SchoolHolidays in Germany Nordrhein-Westfalen 

### ISSUE THREAD

**Issue by JarekJ1986** [balmli/no.almli.publicholidays#13]
Hello,
I'm testing your App on Homey an i have Problems with the School holiday card.
In Germany Nordrhein-Westfalen we have today and the next two weeks SchoolHolidays, but your App got a different result for today.

**Comment by balmli** [comment]
"Is school holiday" was removed since v. 1.2.0

**Comment by JarekJ1986** [comment]
Thanks for the feedback

Bjørnar Almli ***@***.***> schrieb am Di., 20. Dez. 2022,
09:42:
