### ISSUE TITLE
Netherlands working day not correct

### ISSUE THREAD

**Issue by ollifdgmdg** [balmli/no.almli.publicholidays#14]
I'm having an issue with the public holidays in the Neterhlands.

![Schermafbeelding 2022-11-22 195859](https://user-images.githubusercontent.com/110771005/203398703-6b7ccbe9-b778-45e7-9d66-79b643603af9.png)

On Today (22-11-2022) is a working day I get a not true message.

What can be wrong?

**Comment by balmli** [comment]
Try deleting and re-adding the "Is working day" - card
