### ISSUE TITLE
Request: Tag which public holiday it is

### ISSUE THREAD

**Issue by Marc1979** [balmli/no.almli.publicholidays#2]
Could you make an tag in the app with which public holiday it is?
The i can make different flows on different holidays. (Example play christmas music when it is christmas..etc)

**Comment by balmli** [comment]
Yes, I also think that would be a good idea.

This app has just conditions ("and") for the flow, and have to figure out how to use tokens (tags) for conditions.

**Comment by Marc1979** [comment]
Thanks...take you're time!

**Comment by balmli** [comment]
Plan is to:

* create three global tokens for name of the holiday for yesterday, today and tomorrow
* the country used in a flow will be used for the tokens.  So no config is necessary
* the tokens are updated at midnight

Will be in v. 1.0.9

**Comment by Marc1979** [comment]
Great!

**Comment by balmli** [comment]
Released v. 1.0.11 now with this fix.
