### ISSUE TITLE
AND confirmations

### ISSUE THREAD

**Issue by Phunkay** [balmli/no.almli.publicholidays#4]
One of my flows wasn't triggered the last couple of days and I found out it was caused by the Public Holiday AND Card.
I've found that none of the AND cards work unless I invert them, and then they all get confirmed (as shown in the test flow below). I've tried resetting the app (v1.0.11) but it hasn't helped.

![image](https://user-images.githubusercontent.com/22442908/57527849-fa82a080-7330-11e9-9496-a034b7c50ae4.png)

**Comment by balmli** [comment]
Hi, 

You can take a look in this file:
https://github.com/balmli/no.almli.publicholidays/blob/master/lib/holidays_list.js

And search for "BE-2019-05-" for Belgium holidays.

Please let me know if the list of holidays for Beligum is wrong.

**Comment by balmli** [comment]
There seems to be a bug with the "Is workingday" - condition.

Thanks for reporting this.

Will try to fix as fast as possible.

**Comment by balmli** [comment]
Here is a flow to check for "observance" tomorrow.. Mothers' Day, in Belgium tomorrow..

And you'll see that that works OK.

<img width="299" alt="Skjermbilde 2019-05-11 kl  07 15 00" src="https://user-images.githubusercontent.com/1215481/57565364-e71d1700-73bc-11e9-9c3a-7e9cdb4e2758.png">

**Comment by balmli** [comment]
Fixed in v. 1.0.12.

**Comment by balmli** [comment]
V. 1.0.12 is in app store now
