### ISSUE TITLE
Request: add school holiday, schools are closed for Germany

### ISSUE THREAD

**Issue by madmax75** [balmli/no.almli.publicholidays#6]
Hello, thanks for this great app. Is it possible to integrate the German school holidays into the app?

**Comment by balmli** [comment]
Will be added in v.1.0.15

**Comment by madmax75** [comment]
Tanks for this implementation

**Comment by balmli** [comment]
Ready in the app store now, as beta.

Please test :-)

**Comment by madmax75** [comment]
Hi. It doesn’t work. It’s now school holidays and the flow says it’s no school holiday.

**Comment by balmli** [comment]
What country did you check for ?

**Comment by balmli** [comment]
Here is the data that is used in the app: https://github.com/commenthol/date-holidays/tree/master/data/countries

And here is the list of countries / areas supported: https://github.com/balmli/no.almli.publicholidays/blob/master/lib/countries.js

**Comment by madmax75** [comment]
Hi, 
I think we talked at cross purposes. I was thinking about this one during school holidays:

As an example:

https://publicholidays.de/school-holidays/north-rhine-westphalia

**Comment by balmli** [comment]
Sorry, but maybe this could be a separate app for school holidays for Germany.
