### ISSUE TITLE
Holidays (Netherlands)

### ISSUE THREAD

**Issue by Munnikie** [balmli/no.almli.publicholidays#7]
My kids are now on Holiday, but when I use this in a flow to control a morning alarm, it does not see it as an Holiday.
What's your source for the holliday's in the Netherlands?

Kind Regards,

Robert

**Comment by balmli** [comment]
This is the source:
https://www.npmjs.com/package/date-holidays

And here is the list for NL:

https://github.com/commenthol/date-holidays/blob/master/data/countries/NL.yaml
