### ISSUE TITLE
German School Holidays (Hessen)

### ISSUE THREAD

**Issue by andreasbeck** [balmli/no.almli.publicholidays#9]
Hello ,

I just tried to managed my Homeys, day/working day behaviour based on school holidays. Unfortunately the school holidays for Hessen are not available, right now there are holidays, but Homey does not seem to see them.

Could you check this?

Regards
Andreas

**Comment by balmli** [comment]
The app uses this module:
https://www.npmjs.com/package/date-holidays

Only holidays added to that will be supported by the app.
